#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'vagrant-ohai', :git => "https://github.com/tknerr/cookbooks-vagrant-ohai.git"
cookbook 'icinga',       :git => "https://github.com/mdxp/icinga-cookbook.git"